"""empty message

Revision ID: 11ea31a4a7bc
Revises: ab0966e199d2
Create Date: 2019-04-13 15:38:06.743093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11ea31a4a7bc'
down_revision = 'ab0966e199d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.Integer(), nullable=False))
    op.drop_column('user', 'account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
