"""empty message

Revision ID: 14776758607c
Revises: acbfbbeb1c2e
Create Date: 2019-04-06 20:42:43.956497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14776758607c'
down_revision = 'acbfbbeb1c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydrology_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hydrology_data_route', sa.String(length=100), nullable=False),
    sa.Column('hydrology_data_name', sa.String(length=100), nullable=False),
    sa.Column('hydrology_data_time', sa.DateTime(), nullable=False),
    sa.Column('hydrology_data_format', sa.String(length=100), nullable=False),
    sa.Column('hydrology_data_kind', sa.String(length=100), nullable=False),
    sa.Column('hydrology_data_refresh', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hydrology_data')
    # ### end Alembic commands ###
