"""empty message

Revision ID: 1a50a8732e3b
Revises: 14776758607c
Create Date: 2019-04-06 23:30:05.456736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a50a8732e3b'
down_revision = '14776758607c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hydrology_data', sa.Column('data_format', sa.String(length=100), nullable=False))
    op.add_column('hydrology_data', sa.Column('data_kind', sa.String(length=100), nullable=False))
    op.add_column('hydrology_data', sa.Column('data_name', sa.String(length=100), nullable=False))
    op.add_column('hydrology_data', sa.Column('data_refresh', sa.String(length=100), nullable=False))
    op.add_column('hydrology_data', sa.Column('data_route', sa.String(length=100), nullable=False))
    op.add_column('hydrology_data', sa.Column('data_time', sa.DateTime(), nullable=False))
    op.drop_column('hydrology_data', 'hydrology_data_route')
    op.drop_column('hydrology_data', 'hydrology_data_refresh')
    op.drop_column('hydrology_data', 'hydrology_data_time')
    op.drop_column('hydrology_data', 'hydrology_data_format')
    op.drop_column('hydrology_data', 'hydrology_data_kind')
    op.drop_column('hydrology_data', 'hydrology_data_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hydrology_data', sa.Column('hydrology_data_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('hydrology_data', sa.Column('hydrology_data_kind', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('hydrology_data', sa.Column('hydrology_data_format', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('hydrology_data', sa.Column('hydrology_data_time', mysql.DATETIME(), nullable=False))
    op.add_column('hydrology_data', sa.Column('hydrology_data_refresh', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('hydrology_data', sa.Column('hydrology_data_route', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('hydrology_data', 'data_time')
    op.drop_column('hydrology_data', 'data_route')
    op.drop_column('hydrology_data', 'data_refresh')
    op.drop_column('hydrology_data', 'data_name')
    op.drop_column('hydrology_data', 'data_kind')
    op.drop_column('hydrology_data', 'data_format')
    # ### end Alembic commands ###
