"""empty message

Revision ID: 3a841dec8807
Revises: 54bdd8e17a84
Create Date: 2019-04-09 18:24:49.135800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a841dec8807'
down_revision = '54bdd8e17a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemistry_data', sa.Column('uid_data', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chemistry_data', 'data', ['uid_data'], ['id'])
    op.add_column('hydrology_data', sa.Column('uid_data', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hydrology_data', 'data', ['uid_data'], ['id'])
    op.add_column('organism_data', sa.Column('uid_data', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organism_data', 'data', ['uid_data'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organism_data', type_='foreignkey')
    op.drop_column('organism_data', 'uid_data')
    op.drop_constraint(None, 'hydrology_data', type_='foreignkey')
    op.drop_column('hydrology_data', 'uid_data')
    op.drop_constraint(None, 'chemistry_data', type_='foreignkey')
    op.drop_column('chemistry_data', 'uid_data')
    # ### end Alembic commands ###
