"""empty message

Revision ID: 54cc1b3b6711
Revises: 681488cb6240
Create Date: 2019-04-05 16:28:26.934777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54cc1b3b6711'
down_revision = '681488cb6240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organism_data', sa.Column('organism_data_kind', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organism_data', 'organism_data_kind')
    # ### end Alembic commands ###
