"""empty message

Revision ID: 57d2a0de8607
Revises: f3019aecd6cd
Create Date: 2019-04-08 15:20:07.441898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57d2a0de8607'
down_revision = 'f3019aecd6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemistry_data', sa.Column('uid_chemistry', sa.Integer(), nullable=True))
    op.drop_constraint('chemistry_data_ibfk_1', 'chemistry_data', type_='foreignkey')
    op.create_foreign_key(None, 'chemistry_data', 'marine_chemistry', ['uid_chemistry'], ['id'])
    op.drop_column('chemistry_data', 'uid_hydrology')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemistry_data', sa.Column('uid_hydrology', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chemistry_data', type_='foreignkey')
    op.create_foreign_key('chemistry_data_ibfk_1', 'chemistry_data', 'marine_chemistry', ['uid_hydrology'], ['id'])
    op.drop_column('chemistry_data', 'uid_chemistry')
    # ### end Alembic commands ###
