"""empty message

Revision ID: 5990c32b8702
Revises: d706e4f23a61
Create Date: 2019-04-07 11:47:03.315810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5990c32b8702'
down_revision = 'd706e4f23a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organism_data', sa.Column('data_format', sa.String(length=100), nullable=False))
    op.add_column('organism_data', sa.Column('data_kind', sa.String(length=100), nullable=False))
    op.add_column('organism_data', sa.Column('data_name', sa.String(length=100), nullable=False))
    op.add_column('organism_data', sa.Column('data_refresh', sa.String(length=100), nullable=False))
    op.add_column('organism_data', sa.Column('data_route', sa.String(length=100), nullable=False))
    op.add_column('organism_data', sa.Column('data_time', sa.DateTime(), nullable=False))
    op.drop_column('organism_data', 'organism_data_route')
    op.drop_column('organism_data', 'organism_data_format')
    op.drop_column('organism_data', 'organism_data_kind')
    op.drop_column('organism_data', 'organism_data_name')
    op.drop_column('organism_data', 'organism_data_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organism_data', sa.Column('organism_data_time', mysql.DATETIME(), nullable=False))
    op.add_column('organism_data', sa.Column('organism_data_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('organism_data', sa.Column('organism_data_kind', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('organism_data', sa.Column('organism_data_format', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('organism_data', sa.Column('organism_data_route', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('organism_data', 'data_time')
    op.drop_column('organism_data', 'data_route')
    op.drop_column('organism_data', 'data_refresh')
    op.drop_column('organism_data', 'data_name')
    op.drop_column('organism_data', 'data_kind')
    op.drop_column('organism_data', 'data_format')
    # ### end Alembic commands ###
