"""empty message

Revision ID: 64dd8fd9582b
Revises: 51c3b20d471e
Create Date: 2019-04-05 16:19:10.653176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dd8fd9582b'
down_revision = '51c3b20d471e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organism_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route', sa.String(length=100), nullable=False),
    sa.Column('data_set_name', sa.DateTime(), nullable=False),
    sa.Column('data_set_size', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organism_data')
    # ### end Alembic commands ###
