"""empty message

Revision ID: 6ced38ceee38
Revises: 5990c32b8702
Create Date: 2019-04-07 11:49:01.247124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ced38ceee38'
down_revision = '5990c32b8702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organism_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_route', sa.String(length=100), nullable=False),
    sa.Column('data_name', sa.String(length=100), nullable=False),
    sa.Column('data_time', sa.DateTime(), nullable=False),
    sa.Column('data_format', sa.String(length=100), nullable=False),
    sa.Column('data_kind', sa.String(length=100), nullable=False),
    sa.Column('data_refresh', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organism_data')
    # ### end Alembic commands ###
