"""empty message

Revision ID: ab0966e199d2
Revises: 38f42ebb533a
Create Date: 2019-04-13 15:36:10.521673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab0966e199d2'
down_revision = '38f42ebb533a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
