"""empty message

Revision ID: c08cb127ce56
Revises: 54cc1b3b6711
Create Date: 2019-04-06 08:48:52.514000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c08cb127ce56'
down_revision = '54cc1b3b6711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organism_data', sa.Column('organism_data_route', sa.String(length=100), nullable=False))
    op.drop_column('organism_data', 'organism_data_self')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organism_data', sa.Column('organism_data_self', mysql.TEXT(), nullable=False))
    op.drop_column('organism_data', 'organism_data_route')
    # ### end Alembic commands ###
