"""empty message

Revision ID: c53cc56b029b
Revises: e16394682414
Create Date: 2019-04-03 17:11:04.834817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53cc56b029b'
down_revision = 'e16394682414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('button_link', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'button_link')
    # ### end Alembic commands ###
