"""empty message

Revision ID: d4b0eaf305a2
Revises: c83ab55ec76c
Create Date: 2019-04-07 16:37:47.452646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b0eaf305a2'
down_revision = 'c83ab55ec76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hydrology_data', sa.Column('down_time', sa.Integer(), nullable=False))
    op.add_column('organism_data', sa.Column('down_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organism_data', 'down_time')
    op.drop_column('hydrology_data', 'down_time')
    # ### end Alembic commands ###
