"""empty message

Revision ID: d706e4f23a61
Revises: 1a50a8732e3b
Create Date: 2019-04-06 23:32:37.913669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd706e4f23a61'
down_revision = '1a50a8732e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydrology_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_route', sa.String(length=100), nullable=False),
    sa.Column('data_name', sa.String(length=100), nullable=False),
    sa.Column('data_time', sa.DateTime(), nullable=False),
    sa.Column('data_format', sa.String(length=100), nullable=False),
    sa.Column('data_kind', sa.String(length=100), nullable=False),
    sa.Column('data_refresh', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hydrology_data')
    # ### end Alembic commands ###
